name: Hatter
options:
  bundleIdPrefix: me.jappie
  deploymentTarget:
    iOS: "15.0"

targets:
  Hatter:
    type: application
    platform: iOS
    sources:
      - Hatter
    info:
      path: Hatter/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSLocationWhenInUseUsageDescription: "This app needs your location."
        NSBluetoothAlwaysUsageDescription: "This app needs Bluetooth access."
        NSCameraUsageDescription: "This app needs camera access."
        NSMicrophoneUsageDescription: "This app needs microphone access."
        NSContactsUsageDescription: "This app needs access to your contacts."
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.jappie.hatter
        CODE_SIGN_ENTITLEMENTS: Hatter/Hatter.entitlements
        SWIFT_OBJC_BRIDGING_HEADER: Hatter/Hatter-Bridging-Header.h
        LIBRARY_SEARCH_PATHS: ["$(inherited)", "$(PROJECT_DIR)/lib"]
        HEADER_SEARCH_PATHS: ["$(inherited)", "$(PROJECT_DIR)/include"]
        OTHER_LDFLAGS: ["$(inherited)", "-lHatter", "-lz", "-liconv", "-lffi", "-lc++", "-framework", "AVFoundation", "-framework", "AuthenticationServices", "-framework", "Contacts", "-framework", "CoreLocation", "-framework", "CoreBluetooth", "-framework", "WebKit", "-framework", "MapKit", "-framework", "QuartzCore"]
