name: Hatter
options:
  bundleIdPrefix: me.jappie
  deploymentTarget:
    watchOS: "9.0"

targets:
  Hatter:
    type: application
    platform: watchOS
    sources:
      - Hatter
    info:
      path: Hatter/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        WKApplication: true
        WKRunsIndependentlyOfCompanionApp: true
        WKCompanionAppBundleIdentifier: me.jappie.hatter
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.jappie.hatter.watchkitapp
        CODE_SIGN_ENTITLEMENTS: Hatter/Hatter.entitlements
        SWIFT_OBJC_BRIDGING_HEADER: Hatter/Hatter-Bridging-Header.h
        LIBRARY_SEARCH_PATHS: ["$(inherited)", "$(PROJECT_DIR)/lib"]
        HEADER_SEARCH_PATHS: ["$(inherited)", "$(PROJECT_DIR)/include"]
        OTHER_LDFLAGS: ["$(inherited)", "-lHatter", "-lz", "-liconv", "-lffi", "-lc++", "-framework", "AuthenticationServices"]

  HatterUITests:
    type: bundle.ui-testing
    platform: watchOS
    sources:
      - path: HatterUITests
        optional: true
    dependencies:
      - target: Hatter
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.jappie.hatter.watchkitapp.uitests
